-- SQL
CREATE TABLE PRICE (
						  DEALID INT,
						  PRICE FLOAT
);

INSERT INTO PRICE VALUES(1, 0.3);
INSERT INTO PRICE VALUES(2, 4);
INSERT INTO PRICE VALUES(3, 7);
INSERT INTO PRICE VALUES(2, 10);
INSERT INTO PRICE VALUES(5, 1.6);
INSERT INTO PRICE VALUES(6, 8);


CREATE TABLE DEAL (
				  DEALID INT PRIMARY KEY,
				  NAME VARCHAR
);

INSERT INTO DEAL VALUES(1, 'A');
INSERT INTO DEAL VALUES(2, 'B');
INSERT INTO DEAL VALUES(3, 'C');
INSERT INTO DEAL VALUES(4, 'D');
INSERT INTO DEAL VALUES(5, 'E');
INSERT INTO DEAL VALUES(6, 'F');